apiVersion: v1
name: dns-network-policy-operator
version: [[ .Version ]]
appVersion: "[[ .AppVersion ]]"
description: dns-network-policy-operator manages Kubernetes network policies with DNS-based egress rules support.
home: https://github.com/giantswarm/dns-network-policy-operator
