kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{tpl .Values.resource.default.name  . }}
  namespace: {{ tpl .Values.resource.default.namespace  . }}
  labels:
    giantswarm.io/service-type: "managed"
    app: {{ .Values.project.name }}
rules:
- apiGroups: ["example.giantswarm.io"]
  resources: ["dnsnetworkpolicies"]
  verbs: ["*"]
- apiGroups: ["extensions", "networking.k8s.io"]
  resources: ["networkpolicies"]
  verbs: ["*"]
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["*"]
- apiGroups:
  - extensions
  resources:
  - podsecuritypolicies
  resourceNames:
  - {{tpl .Values.resource.default.name  . }}
  verbs:
  - use
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{tpl .Values.resource.default.name  . }}
  labels:
    giantswarm.io/service-type: "managed"
    app: {{ .Values.project.name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{tpl .Values.resource.default.name  . }}
subjects:
- kind: ServiceAccount
  name: {{tpl .Values.resource.default.name  . }}
  namespace: {{ tpl .Values.resource.default.namespace  . }}

